config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions, only: [:index, :create, :destroy]

  resources :messages, only: [:index, :create]
  get "messages/thread/:listing_id/:user_id", to: "messages#show", as: :message_thread

  resources :transactions, only: [:index, :show, :update]
  resources :listings, only: [:index, :show]

  resources :listings do
    resources :saved_items, only: [:create, :destroy]
  end

  resources :my_listings, except: [:show]
  get "home/index"
  devise_for :users

  devise_scope :user do
    root to: "devise/registrations#new"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :saved_items, dependent: :destroy
  has_many :saved_by_users, through: :saved_items, source: :user

  validates :title, :authors, :description, :listing_type, :university, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}, allow_nil: true

  def self.ransackable_attributes(auth_object = nil)
    %w[title authors listing_type price isbn course_number university updated_at created_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[images_attachments images_blobs user]
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    base_scope = Listing.where(status: "Available")
    if current_user&.university.present?
      base_scope = base_scope.where(university: current_user.university)
    end
    @q = base_scope.ransack(params[:q])
    @selected_search = params[:q]
    @selected_input = params.dig(:q, :selected_input) || "title"
    @listings = params[:q].present? ? @q.result(distinct: true) : []

    if current_user && params[:q].present?
      @existing_subscription = current_user.subscriptions.find_by(query_params: search_params)
    end
  end

  private

  def search_params
    params.require(:q).permit(:title_cont, :authors_cont, :isbn_cont, :course_number_cont, :listing_type_eq, :sorts, :selected_input)
  rescue ActionController::ParameterMissing
    {}
  end

  def show
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/index.html.erb
<div class="flex flex-col items-center">
  <div class="absolute top-5 left-5 font-bold text-2xl">Book<span class="text-blue-500">Bridge</span></div>
  <div class="mt-15">
    <%= search_form_for @q, url: listings_path, method: :get, html: { class: "flex flex-col items-center" } do |f| %>
      <div class="absolute top-5 left-5 font-bold text-2xl">
        Book<span class="text-blue-500">Bridge</span>
      </div>
      <div class=" grid grid-cols-[8fr_4fr_4fr_4fr_1fr] gap-2 mt-4 " data-controller="search">
        <%= f.search_field :title_cont, placeholder: "Search by title", class: "input bg-transparent w-full border border-gray-400 rounded-lg", "data-search-target": "optionA", value: params.dig(:q, :title_cont) %>
        <%= f.search_field :authors_cont, placeholder: "Search by authors", class: "input bg-transparent w-full border border-gray-400 rounded-lg", "data-search-target": "optionB", value: params.dig(:q, :authors_cont) %>
        <%= f.search_field :isbn_cont, placeholder: "Search by ISBN", class: "input bg-transparent w-full border border-gray-400 rounded-lg", "data-search-target": "optionC", value: params.dig(:q, :isbn_cont) %>
        <%= f.search_field :course_number_cont, placeholder: "Search by course number", class: "input bg-transparent w-full border border-gray-400 rounded-lg", "data-search-target": "optionD", value: params.dig(:q, :course_number_cont) %>
        <select class="select border border-gray-400 bg-transparent rounded-lg" data-search-target="searchInput" data-action="change->search#updateVisibility" name="q[selected_input]">
          <option value="title" <%= @selected_input == "title" ? "selected" : "" %>>Title</option>
          <option value="authors" <%= @selected_input == "authors" ? "selected" : "" %>>Authors</option>
          <option value="isbn" <%= @selected_input == "isbn" ? "selected" : "" %>>ISBN</option>
          <option value="course_number" <%= @selected_input == "course_number" ? "selected" : "" %>>Course Number</option>
        </select>
        <%= f.select :listing_type_eq, options_for_select([ ["Borrow", "Lend"], ["Purchase", "Sell"], ["Either", ""] ], params.dig(:q, :listing_type_eq)), { include_blank: "Select Listing Type" }, class: "select border border-gray-400 rounded-lg bg-transparent" %>
        <%= f.select :sorts, options_for_select([ ["Title (A-Z)", "title asc"], ["Title (Z-A)", "title desc"], ["Price (Low to High)", "price asc"], ["Price (High to Low)", "price desc"], ["Most Recent", "created_at desc"], ["Oldest", "created_at asc"] ], params.dig(:q, :sorts)), { include_blank: "Sort by" }, class: "select border border-gray-400 rounded-lg bg-transparent" %>
        <button type="submit" class="bg-blue-500 text-white w-10 px-2.5 py-2 rounded-xl hover:bg-blue-600 hover:cursor-pointer transition duration-300 ease-in-out">
            <svg width="22px" height="22px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
              <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
              <g id="SVGRepo_iconCarrier">
                <path d="M15.7955 15.8111L21 21M18 10.5C18 14.6421 14.6421 18 10.5 18C6.35786 18 3 14.6421 3 10.5C3 6.35786 6.35786 3 10.5 3C14.6421 3 18 6.35786 18 10.5Z" stroke="#ffffffff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"></path>
              </g>
            </svg>
          </button>
        </div>
      <% end %>
    </div>
    <% if params[:q].blank? && @listings.empty? %>
      <div class="mt-10 w-[65%] min-h-[70vh] flex items-center justify-center">
        <p class="text-gray-800 text-3xl">Looks like you haven't searched for anything</p>
      </div>
    <% elsif @listings.empty? %>
      <div class="mt-10 w-[65%] min-h-[70vh] flex flex-col items-center justify-center gap-4">
        <p class="text-gray-800 text-3xl">Woah! Looks like there’s no book to be found.</p>
        <% if current_user && params[:q].present? %>
          <% if @existing_subscription %>
            <div class="flex items-center gap-3">
              <div class="flex items-center bg-green-100 text-green-700 px-5 py-2 rounded-md text-sm font-medium gap-2">
                <!-- All set icon -->
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6"><path d="M5.85 3.5a.75.75 0 0 0-1.117-1 9.719 9.719 0 0 0-2.348 4.876.75.75 0 0 0 1.479.248A8.219 8.219 0 0 1 5.85 3.5ZM19.267 2.5a.75.75 0 1 0-1.118 1 8.22 8.22 0 0 1 1.987 4.124.75.75 0 0 0 1.48-.248A9.72 9.72 0 0 0 19.266 2.5Z" /><path fill-rule="evenodd" d="M12 2.25A6.75 6.75 0 0 0 5.25 9v.75a8.217 8.217 0 0 1-2.119 5.52.75.75 0 0 0 .298 1.206c1.544.57 3.16.99 4.831 1.243a3.75 3.75 0 1 0 7.48 0 24.583 24.583 0 0 0 4.83-1.244.75.75 0 0 0 .298-1.205 8.217 8.217 0 0 1-2.118-5.52V9A6.75 6.75 0 0 0 12 2.25ZM9.75 18c0-.034 0-.067.002-.1a25.05 25.05 0 0 0 4.496 0l.002.1a2.25 2.25 0 1 1-4.5 0Z" clip-rule="evenodd" /></svg>
                All set!
              </div>
              <%= button_to subscription_path(@existing_subscription), method: :delete, form: { class: 'inline' }, class: 'bg-red-100 text-red-600 hover:bg-red-200 rounded-md px-3 py-2 flex items-center justify-center transition' do %>
                <!-- Delete icon -->
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6"><path d="M3.53 2.47a.75.75 0 0 0-1.06 1.06l18 18a.75.75 0 1 0 1.06-1.06l-18-18ZM20.57 16.476c-.223.082-.448.161-.674.238L7.319 4.137A6.75 6.75 0 0 1 18.75 9v.75c0 2.123.8 4.057 2.118 5.52a.75.75 0 0 1-.297 1.206Z" /><path fill-rule="evenodd" d="M5.25 9c0-.184.007-.366.022-.546l10.384 10.384a3.751 3.751 0 0 1-7.396-1.119 24.585 24.585 0 0 1-4.831-1.244.75.75 0 0 1-.298-1.205A8.217 8.217 0 0 0 5.25 9.75V9Zm4.502 8.9a2.25 2.25 0 1 0 4.496 0 25.057 25.057 0 0 1-4.496 0Z" clip-rule="evenodd" /></svg>
              <% end %>
            </div>
          <% else %>
            <%= form_with url: subscriptions_path, method: :post, class: 'flex items-center gap-3' do %>
              <%# Pass through the ransack query params to create subscription %>
              <% params[:q].each do |k,v| %>
                <%= hidden_field_tag "q[#{k}]", v %>
              <% end %>
              <button type="submit" class="flex items-center gap-2 bg-blue-100 text-blue-700 hover:bg-blue-200 px-5 py-2 rounded-md text-sm font-medium transition">
                <!-- Set arrival notification icon -->
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6"><path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0M3.124 7.5A8.969 8.969 0 0 1 5.292 3m13.416 0a8.969 8.969 0 0 1 2.168 4.5" /></svg>
                Set arrival notification
              </button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="mt-4 w-[65%] min-h-[70vh] flex flex-col">
        <div class="flex items-center justify-between">
          <p> <%= @listings.count %> results found for your search. </p>
        </div>
        <% @listings.each do |listing| %>
          <% saved_item = current_user.saved_items.find_by(listing_id: listing.id) %>
          <%= render ListingCardComponent.new(listing: listing, mode: :saved, saved_item: saved_item) %>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/listings/show.html.erb
<div class="flex justify-center"><!-- Page wrapper -->
  <div class="absolute top-5 left-5 font-bold text-2xl">Book<span class="text-blue-500">Bridge</span></div>
  <div class="mt-15 w-[65%] min-h-[80vh] flex flex-col rounded-lg">
    <div> <!-- Back button -->
      <%= link_to "Back", :back, class: "text-gray-700 hover:underline" %>
    </div>
    <div class="mt-4 flex flex-row w-full gap-8"> <!-- Main book content -->
      <div class="w-1/3" data-controller="image-switch"> <!-- Image and Image controller -->
        <% if @listing.images.attached? %>
          <%= image_tag  @listing.images.first, alt: @listing.title, class: "w-full aspect-[3/4] object-cover rounded-lg", "data-image-switch-target": "mainImage" %>
          <div class="mt-4 flex gap-2">
            <% @listing.images.each_with_index do |image, index| %>
              <%= image_tag image, 
          alt: @listing.title, 
          class: "w-16 aspect-[3/4] object-cover rounded-lg cursor-pointer border-2 hover:border-blue-500 #{index == 0 ? 'border-blue-500' : 'border-none'}", 
          "data-image-switch-target": "thumbnail", 
          "data-action": "click->image-switch#updateImage", 
          "data-image-url": url_for(image) %>
            <% end %>
          </div>
        <% else %>
          <div class="w-full aspect-[3/4] bg-gray-100 border flex items-center justify-center text-gray-400 text-xs rounded">
            No Image
          </div>
        <% end %>
      </div>
      <div class="w-2/3 flex flex-col"> <!-- Book details -->
        <div> <!-- Title and author -->
          <h1 class="text-2xl font-bold"><%= @listing.title %></h1>
          <p class="text-gray-600 text-lg"><%= @listing.authors %></p>
        </div>
        <div class="mt-4 flex flex-row gap-4"> <!-- Date, Course, ISBN, Type -->
          <p class="text-gray-600">Published on: <%= @listing.created_at.strftime("%B %d, %Y") %></p>
          <p class="text-gray-600">Course: <%= @listing.course_number %></p>
          <p class="text-gray-600">ISBN: <%= @listing.isbn %></p>
          <p class="text-gray-600">Type: <%= @listing.listing_type %></p>
        </div>
        <div class="mt-4"> <!-- Price if available -->
          <p class="text-gray-800 font-bold text-xl"><%= number_to_currency(@listing.price) %></p>
        </div>
        <div class="mt-4 flex flex-row gap-4"> <!-- Message and Save buttons -->
          <% unless current_user == @listing.user %>
            <%= link_to "Message",
        message_thread_path(listing_id: @listing.id, user_id: @listing.user_id), class: "px-4 py-2 bg-blue-500 text-white rounded" %>
            <% if current_user.saved_listings.include?(@listing) %>
              <%= button_to listing_saved_item_path(@listing), method: :delete, class: "bg-green-100 hover:bg-green-200 p-3 rounded-lg" do %>
                <svg fill="#00D438" width="20px" height="20px" viewBox="0 0 24 24" id="bookmark" data-name="Flat Color" xmlns="http://www.w3.org/2000/svg" class="icon flat-color">
                  <path id="primary" d="M18,2H6A2,2,0,0,0,4,4V21a1,1,0,0,0,.5.86,1,1,0,0,0,1,0L12,18.15l6.5,3.72A1,1,0,0,0,19,22a.9.9,0,0,0,.5-.14A1,1,0,0,0,20,21V4A2,2,0,0,0,18,2Z" style="fill: #00D438;"></path>
                </svg>
              <% end %>
            <% else %>
              <%= button_to listing_saved_items_path(@listing), method: :post, class: "bg-green-100 hover:bg-green-200 p-3 rounded-lg" do %>
                <svg fill="none" stroke="#00D438" stroke-width="2" width="20px" height="20px" viewBox="0 0 24 24" id="bookmark" data-name="Flat Color" xmlns="http://www.w3.org/2000/svg" class="icon flat-color">
                  <path id="primary" d="M18,2H6A2,2,0,0,0,4,4V21a1,1,0,0,0,.5.86,1,1,0,0,0,1,0L12,18.15l6.5,3.72A1,1,0,0,0,19,22a.9.9,0,0,0,.5-.14A1,1,0,0,0,20,21V4A2,2,0,0,0,18,2Z" style="stroke: #00D438;"></path>
                </svg>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="mt-4"> <!-- User.find by user_id, and Description -->
          <p class="text-gray-600">Listed by: <%= User.find(@listing.user_id).name %></p>
          <p class="text-gray-600 mt-2"><%= @listing.description %></p>
        </div>
      </div>
    </div>
  </div>
</div>