config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions, only: [:index, :create, :destroy]

  resources :messages, only: [:index, :create]
  get "messages/thread/:listing_id/:user_id", to: "messages#show", as: :message_thread

  resources :transactions, only: [:index, :show, :update]
  resources :listings, only: [:index, :show]

  resources :listings do
    resources :saved_items, only: [:create, :destroy]
  end

  resources :my_listings, except: [:show]
  get "home/index"
  devise_for :users

  devise_scope :user do
    root to: "devise/registrations#new"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/my_listings_controller.rb
class MyListingsController < ApplicationController
  before_action :set_listing, only: %i[edit update destroy]

  def index
    @listings = current_user.listings
    @saved_listings = current_user.saved_listings.includes(:user, images_attachments: :blob)
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)
    @listing.university = current_user.university
    if @listing.save
      redirect_to my_listings_path, notice: "Listing created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to my_listings_path, notice: "Listing updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    redirect_to my_listings_path, notice: "Listing deleted successfully."
  end

  private

  def set_listing
    @listing = current_user.listings.find(params[:id])
  end

  def listing_params
    params.expect(listing: [:isbn, :title, :authors, :status, :edition, :course_number, :description, :listing_type, :price, images: []])
  end
end

app/helpers/my_listings_helper.rb
module MyListingsHelper
end

app/views/my_listings/_form.html.erb
<%= form_with model: @listing, url: @listing.persisted? ? my_listing_path(@listing) : my_listings_path, method: @listing.persisted? ? :patch : :post do |form| %>
  <div class="flex flex-row">
    <div class="ml-5 w-[40%]" >
      <div class="custom-file-upload" data-controller="clear-files">
        <label for="image-input" id="image-label" class="custom-label w-full border border-gray-300 border-dashed p-2 rounded-lg h-96 flex flex-col items-center justify-center cursor-pointer text-gray-700 hover:bg-gray-100 transition duration-200", data-clear-files-target="imageLabel">
          Add photos
        </label>
        <% @listing.images.each do |image| %>
          <%= form.hidden_field :images, id: "image-existing",  multiple: true, value: image.signed_id %>
        <% end %>
        <%= form.file_field :images, multiple: true, accept: "image/*", id: "image-input", class: "hidden", "data-clear-files-target": "fileInput", "data-action": "change->clear-files#updateImageLabel" %>
      </div>
      <div class="grid grid-cols-4 gap-4 mt-4">
        <% @listing.images.each do |image| %>
          <div class="relative">
            <img src="<%= url_for(image) %>" alt="Listing Image" class="w-full aspect-[3/4] object-cover rounded-lg border border-gray-300">
          </div>
        <% end %>
      </div>
      <button class="mt-4 w-full p-2 bg-red-500 text-white font-semibold rounded-lg hover:bg-red-600 transition duration-300 ease-in-out" onclick="document.getElementById('image-input').value = ''; document.querySelectorAll('#image-existing').forEach(el => el.remove());">
        Clear
      </button>
    </div>
    <div class="flex flex-col ml-15 w-[60%]">
      <div>
        <%= form.input :title, input_html: { class: "w-full", placeholder: "Enter title" }, label: "Book Title" %>
      </div>
      <div class="mt-4 grid grid-cols-[4fr_1fr] gap-4">
        <%= form.input :authors, input_html: { class: "w-full", placeholder: "Enter authors" }, label: "Author(s)" %>
      </div>
      <div class="grid grid-cols-[2fr_1fr] gap-4">
        <%= form.input :isbn, input_html: { class: "w-full", placeholder: "123-456-7890" }, label: "ISBN" %>
        <%= form.input :course_number, class: "ml-2", input_html: { class: "w-full", placeholder: "ABCD 123" }, label: "Course Number" %>
      </div>
      <div class="grid grid-cols-3 gap-4" data-controller="lend-sell">
        <%= form.input :edition, input_html: { placeholder: "3rd Edition" } %>
        <%= form.input :listing_type, as: :select, collection: ["Lend", "Sell"], input_html: { "data-lend-sell-target": "input", "data-action": "change->lend-sell#determinePriceVisibility" } %>
        <div data-lend-sell-target="priceInput" class="invisible">
          <%= form.input :price, as: :integer , input_html: {placeholder: "12.99", step: 0.01}, label: "Price (USD)" %>
        </div>
      </div>
      <div>
        <%= form.input :description, as: :text, input_html: { rows: 5, class: "w-full", placeholder: "Enter description" } %>
      </div>
      <div class="mt-4">
        <%= form.check_box :status, { checked: @listing.status == "Available", class: "checkbox checkbox-sm border-gray-400 checked:border-blue-500 checked:bg-blue-500 checked:text-white rounded-md" }, "Available", "Unavailable" %>
        <%= form.label :status, "Make Available", class: "ml-2 text-gray-700"%>
      </div>
      <div class="mt-4">
        <%= form.submit "Done", class: "w-full p-2 bg-[#D1FFD9] text-[#00D438] font-semibold rounded-lg hover:bg-green-200 hover:cursor-pointer transition duration-300 ease-in-out" %>
      </div>
    <% end %>

app/views/my_listings/_form2.html.erb
<%= form_with model: @listing, url: my_listings_path do |form| %>
  <div class="flex flex-row">
    <div class="ml-5 w-[40%]" >
      <div class="custom-file-upload" data-controller="clear-files">
        <label for="image-input" id="image-label" class="custom-label w-full border border-gray-300 border-dashed p-2 rounded-lg h-96 flex flex-col items-center justify-center cursor-pointer text-gray-700 hover:bg-gray-100 transition duration-200", data-clear-files-target="imageLabel">
          <svg width="32px" height="32px" viewBox="0 0 24.00 24.00" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#545454ff" stroke-width="0">
            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
            <g id="SVGRepo_iconCarrier">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M3.75 4.5L4.5 3.75H10.5L11.25 4.5V10.5L10.5 11.25H4.5L3.75 10.5V4.5ZM5.25 5.25V9.75H9.75V5.25H5.25ZM13.5 3.75L12.75 4.5V10.5L13.5 11.25H19.5L20.25 10.5V4.5L19.5 3.75H13.5ZM14.25 9.75V5.25H18.75V9.75H14.25ZM17.25 20.25H15.75V17.25H12.75V15.75H15.75V12.75H17.25V15.75H20.25V17.25H17.25V20.25ZM4.5 12.75L3.75 13.5V19.5L4.5 20.25H10.5L11.25 19.5V13.5L10.5 12.75H4.5ZM5.25 18.75V14.25H9.75V18.75H5.25Z" fill="#545454ff"></path>
            </g>
          </svg>
          Add photos
        </label>
        <%= form.file_field :images, multiple: true, accept: "image/*", id: "image-input", class: "hidden", "data-clear-files-target": "fileInput", "data-action": "change->clear-files#updateImageLabel" %>
      </div>
      <button class="mt-4 w-full p-2 bg-red-500 text-white font-semibold rounded-lg hover:bg-red-600 hover:cursor-pointer transition duration-300 ease-in-out" onclick="document.getElementById('image-input').value = ''">
        Clear
      </button>
    </div>
    <div class="flex flex-col ml-15 w-[60%]">
      <div>
        <%= form.label :title, "Book Title", class: "block font-medium text-gray-700" %>
        <%= form.text_field :title, autofocus: true, placeholder: "Title goes here", class: "mt-1 p-2 w-full border border-gray-400 rounded-lg" %>
        <% if @listing.errors[:title].any? %>
          <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:title].join(", ") %></div>
        <% end %>
      </div>
      <div class="mt-4">
        <%= form.label :authors, "Author(s)", class: "block font-medium text-gray-700" %>
        <%= form.text_field :authors, placeholder: "Author(s) of the book", class: "mt-1 p-2 border border-gray-400 rounded-lg w-[80%]" %>
        <% if @listing.errors[:authors].any? %>
          <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:authors].join(", ") %></div>
        <% end %>
      </div>
      <div class="flex flex-row mt-4">
        <div class="mr-4 w-[65%]">
          <%= form.label :isbn, "ISBN", class: "block font-medium text-gray-700" %>
          <%= form.text_field :isbn, placeholder: "123-456-7890", class: "mt-1 p-2 border border-gray-400 rounded-lg w-full" %>
          <% if @listing.errors[:isbn].any? %>
            <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:isbn].join(", ") %></div>
          <% end %>
        </div>
        <div class="w-[35%]">
          <%= form.label :course_number, "Course Number", class: "block font-medium text-gray-700" %>
          <%= form.text_field :course_number, class: "mt-1 p-2 border border-gray-400 rounded-lg w-full", placeholder: "ABCD 123" %>
          <% if @listing.errors[:course_number].any? %>
            <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:course_number].join(", ") %></div>
          <% end %>
        </div>
      </div>
      <div class="flex flex-row mt-4">
        <div class="mr-4 w-[33%]">
          <%= form.label :edition, "Edition", class: "block font-medium text-gray-700" %>
          <%= form.text_field :edition, placeholder: "1st", class: "mt-1 p-2 border border-gray-400 rounded-lg w-full" %>
          <% if @listing.errors[:edition].any? %>
            <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:edition].join(", ") %></div>
          <% end %>
        </div>
        <div data-controller="lend-sell" class="flex flex-row w-[66%]">
          <div class="w-[50%]">
            <%= form.label :listing_type, "Lend or Sell" %>
            <%= form.select :listing_type,
            [["Lend", "lend"], ["Sell", "sell"]],
            { selected: @listing.listing_type },
            { class: "mt-1 select select-primary w-full p-2 bg-transparent border border-gray-400 rounded-lg", id: "listing-type-select", "data-lend-sell-target": "input", "data-action": "change->lend-sell#determinePriceVisibility" } %>
            <% if @listing.errors[:listing_type].any? %>
              <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:listing_type].join(", ") %></div>
            <% end %>
          </div>
          <div id="price-field" class="ml-4 w-[50%]" data-lend-sell-target="priceInput">
            <%= form.label :price, "Price (USD)", class: "block font-medium text-gray-700" %>
            <%= form.number_field :price, placeholder: "12.99", step: 0.01, class: "mt-1 p-2 border border-gray-400 rounded-lg w-full" %>
            <% if @listing.errors[:price].any? %>
              <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:price].join(", ") %></div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mt-4">
        <%= form.label :description, "Description", class: "block font-medium text-gray-700" %>
        <%= form.text_area :description, placeholder: "Description of the book", class: "mt-1 p-2 border border-gray-400 rounded-lg w-full" %>
        <% if @listing.errors[:description].any? %>
          <div class="text-red-500 text-sm mt-1"><%= @listing.errors[:description].join(", ") %></div>
        <% end %>
      </div>
      <div class="mt-4">
        <%= form.submit "Done", class: "w-full p-2 bg-[#D1FFD9] text-[#00D438] font-semibold rounded-lg hover:bg-green-200 hover:cursor-pointer transition duration-300 ease-in-out" %>
      </div>
    </div>
  </div>
<% end %>

app/views/my_listings/edit.html.erb
<div class="flex flex-col items-center">
  <div class="absolute top-5 left-5 font-bold text-2xl">Book<span class="text-blue-500">Bridge</span></div>
  <div class=" w-[65%] items-center mt-20">
    <h1 class="text-gray-900 font-semibold text-2xl">Edit Listing</h1>
    <p> Update the details about the item</p>
  </div>
  <div class="w-[65%] mt-4">
    <%= render "form", listing: @listing %>
  </div>
</div>

app/views/my_listings/index.html.erb
<div class="flex flex-col items-center" data-controller="dropdown-toggle">
  <div class="absolute top-5 left-5 font-bold text-2xl">Book<span class="text-blue-500">Bridge</span></div>
  <div class=" w-[65%] items-center mt-20">
    <h1 class="text-gray-900 font-semibold text-2xl">My Listings</h1>
  </div>
  <div class="somepeer w-[65%] flex justify-end">
    <select class="select w-50 border border-gray-400 bg-transparent rounded-lg mt-4 mb-4" data-action="change->dropdown-toggle#toggleDropdown" data-dropdown-toggle-target="dropdown">
      <option value="all">My Listings</option>
      <option value="saved">Saved Listings</option>
    </select>
  </div>
  <!-- My Listings -->
  <div class="w-[65%] min-h-[70vh] flex flex-col" data-dropdown-toggle-target="all">
    <% @listings.each do |listing| %>
      <%= render ListingCardComponent.new(listing: listing, mode: :editable) %>
    <% end %>
  </div>
  <!-- Saved Listings -->
  <div class="w-[65%] min-h-[70vh] flex flex-col hidden" data-dropdown-toggle-target="saved">
    <% @saved_listings.each do |listing| %>
      <% saved_item = current_user.saved_items.find_by(listing_id: listing.id) %>
      <%= render ListingCardComponent.new(listing: listing, mode: :saved, saved_item: saved_item) %>
    <% end %>
  </div>
</div>

app/views/my_listings/new.html.erb
<div class="flex flex-col items-center">
  <div class="absolute top-5 left-5 font-bold text-2xl">Book<span class="text-blue-500">Bridge</span></div>
  <div class=" w-[65%] items-center mt-20">
    <h1 class="text-gray-900 font-semibold text-2xl">Add a listing</h1>
    <p> Add all the details about the item</p>
  </div>
  <div class="w-[65%] mt-4">
    <%= render "form", listing: @listing %>
  </div>
</div>